### ISSUE TITLE
[FEATURE] Different DF event returns based on escalation result

### ISSUE THREAD

**Issue by dlassalle** [WideChat/Apps.Salesforce.LiveAgent#6]
Currently we support sending an event to DF when the chat ends.
Break this out into different scenarios with a configurable event for each (i.e. a successful escalation would return with a different event than a failed escalation)

- Agent available and successful escalation
- Agent unavailable, booted back to bot
- Error

**Comment by PrajvalRaval** [comment]
Will be working on this 👍
